version: '3.2'

services:
  micro_boilerplate:
    build: ../
    ports:
      - 3000:3000
    env_file:
      - ./env/test.env
    volumes:
      - type: bind
        source: ../tests
        target: /usr/src/app/tests
    networks:
      - backend
  neo4j_db:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    env_file:
      - ./env/test.env
    volumes:
      - type: bind
        source: ${HOME}/neo4j/test
        target: /data
    networks:
      - backend

networks:
  backend:
    driver: bridge
